### ISSUE TITLE
Middlewares are not working in notFound

### ISSUE THREAD

**Issue by sibbngheid** [GetRayo/rayo.js#135]
**Describe the bug**
Middlewares are set with `.through` is not available on `notFound `handler.

**To Reproduce**
```javascript
const rayo = require('rayo');
const send = require('@rayo/send');

const options = {
  port: 5050,
  onError: (error, req, res) => {
    res.send({success: false, error}, 422);
    // ✅res.send works
  },
  notFound: (req, res) => {
    res.send({success: false, error: req.url + " not found"}, 404);
    // ❌TypeError: res.send is not a function
  }
};

const ray = rayo(options)
  .through(send())

ray.get('/', (req, res, step) => step("error") )

ray.start(({port}) => {
  console.log(`Listening on port http://127.0.0.1:${port}`);
});
```
1) navigate "/" res.send works in onError
2) navigate "/undefinedroute" app crashes

**Expected behavior**
res.send to work on notFound.

Also catch all errors in `onError ` including not found errors.

**Comment by aichholzer** [comment]
Excellent suggestion/finding @sibbngheid -Thank you.
I will work on a fix for this. Feel free to submit a PR if you are up for it.

**Comment by aichholzer** [comment]
@sibbngheid -Here's this one: https://github.com/GetRayo/rayo.js/pull/140
