### ISSUE TITLE
req.ip is null

### ISSUE THREAD

**Issue by sibbngheid** [GetRayo/rayo.js#136]
https://github.com/GetRayo/rayo.js/blob/master/packages/rayo/index.js#L67

Maybe this line should be like `req.ip = ip(req);` But after this change throws an error on line 10:

https://github.com/GetRayo/rayo.js/blob/master/packages/rayo/index.js#L10

`TypeError: Cannot read property 'remoteAddress' of undefined`

**Comment by aichholzer** [comment]
Thank you @sibbngheid -Good catch. I am not sure how I did not see this. 🤔 
https://github.com/GetRayo/rayo.js/pull/138

**Comment by aichholzer** [comment]
Done.
