### ISSUE TITLE
Alias res.header to res.setHeader

### ISSUE THREAD

**Issue by sibbng** [GetRayo/rayo.js#137]
**Is your feature request related to a problem? Please describe.**
Some express middlewares using this to set headers. Example: lusca

**Describe the solution you'd like**
When rayo is compatible with express middlewares maybe should set headers like express.

**Describe alternatives you've considered**
`.through(
    (req, res, step) => {
      res.header = res.setHeader;
      step();
    }`

**Comment by aichholzer** [comment]
@sibbng

> ¹ Rayo is not intended to be an Express replacement, thus the API is similar, inspired-by, but not identical.<br />
> ² Some middleware rely on Express-specific features, which Rayo may or may not implement.
