### ISSUE TITLE
Add caveat to benchmarks

### ISSUE THREAD

**Issue by kamikazechaser** [GetRayo/rayo.js#163]
I think it should be mentioned that Rayo storm takes advantage of all CPU's in the benchmarks (Which is kind of an unfair advantage imho in a fair benachmarking process). Kind of misleading for people who open the page.

**Comment by aichholzer** [comment]
@kamikazechaser -Good point.
Given the description of the benchmark, I would expect people to read up on what `Rayo/Storm` means and make their own conclusions.

**Comment by aichholzer** [comment]
@kamikazechaser 
https://github.com/GetRayo/rayo.js/commit/1b67eeeb9eed41070d1adbcb683e3274aaac5e4b
