### ISSUE TITLE
Fastify with two handlers

### ISSUE THREAD

**Issue by aichholzer** [GetRayo/rayo.js#39]
@mcollina could you shed some light here, please?
Trying to do something like this with `fastify`:
```js
app
  .get(
    '/user/:name',
    (req, res, next) => {
      req.params.name = `Thunderstruck... ${req.params.name}`;
      return next();
    },
    (req, res) => res.end(req.params.name)
  )
  .listen(5050);
```

It's for rayo's bench-marking purposes.
Thank you.

**Comment by mcollina** [comment]
That’s not possible with fastify, as it uses deterministic routing.

**Comment by aichholzer** [comment]
I figured as much... Thought you'd have a trick up your sleeve for this one.
Thank you, nonetheless.
