### ISSUE TITLE
Which runtime is used (on benchmarks) ?

### ISSUE THREAD

**Issue by waghanza** [GetRayo/rayo.js#49]
Hi @aichholzer,

The context described https://github.com/GetRayo/rayo.js/tree/master#how-does-it-compare for how benchmarks are run is very clear.

However, there is no details about runtime used. Do you use something like http://pm2.keymetrics.io/ ?

Regards,

**Comment by aichholzer** [comment]
Just `npm run bench` issued in the CLI and those results, which I get as the response, are the ones in the document. Nothing fancy.

**Comment by waghanza** [comment]
Nop. My question was on `server-side`. How is run targets ? `pm2` or `node` ?

**Comment by aichholzer** [comment]
Just `node`.
