### ISSUE TITLE
Benchmarking question

### ISSUE THREAD

**Issue by waghanza** [GetRayo/rayo.js#83]
Hi,

I can see (on `README`) that comparison with other `node` **frameworks** are made with a concurrency of **1000**.

Why this level of currency ?

Regards,

**Comment by aichholzer** [comment]
Why not?
In this case, concurrency is a random number. It could have been `10` or `100` or `1000` or anything in between. I went for `1000`. As long as every other framework is tested with the same concurrency, it does not really matter.

**Comment by waghanza** [comment]
`crystal` clear. you mean that the most important is to use the same number for each **frameworks**

if I understand, higher the number is, more precise is the gap between each **frameworks** ;-)

**Comment by aichholzer** [comment]
1 core. By default `Rayo` does not do any clustering.
If clustering is enabled then the concurrency would be spread over all cores being used.

**Comment by waghanza** [comment]
ok, thanks
