### ISSUE TITLE
How to serve static files?

### ISSUE THREAD

**Issue by caracal7** [GetRayo/rayo.js#99]
Maybe any example?

**Comment by aichholzer** [comment]
Hello @caracal7 and sorry for the delayed reply.
Currently, there is no native way for `Rayo` to do this. (I have some work in progress on the matter though).

In the meantime, you can do it easily like this:

```js
const rayo = require('rayo');
const send = require('@rayo/send');
const static = require('serve-static')

rayo({ port: 9000 })
  .through(send())
  .get('/css/*', static(`${__dirname}/static`))
  .get('/', (req, res) => {
    res.send({
      message: 'Hello static files!'
    });
  })
  .start();
```

Assuming your folder structure is like:
```
/ root
  / index.js
  / static
    / css
      / test.css
```

You can then call: `http://localhost:9000/` and/or `http://localhost:9000/css/test.css` to hit the corresponding endpoint.

**Comment by caracal7** [comment]
thanks, I will try

**Comment by aichholzer** [comment]
Let me know how it goes.
